export const marketplaceCatalog = [
  { id: "openai", name: "OpenAI", status: "Connected", items: [{ id: "gpt-4.1", name: "GPT-4.1", description: "Generative text", credits: 10 }, { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", description: "Advanced generative text", credits: 15 }, { id: "gpt-image-2", name: "GPT Image 2", description: "Image generation", credits: 8 }, { id: "sora-2", name: "Sora 2", description: "Video generation", credits: 25 }] },
  { id: "astra", name: "Astra", status: "Connected", items: [{ id: "astra-learning", name: "Learning tools", description: "Academy AI tools", credits: 0 }, { id: "astra-codex", name: "Codex workshop", description: "Three-day Codex access", credits: 5 }] },
  { id: "vertex", name: "Vertex AI", status: "Key required", items: [{ id: "gemini-pro", name: "Gemini Pro", description: "Advanced generative text", credits: 12 }, { id: "gemini-flash", name: "Gemini Flash", description: "Fast generative text", credits: 6 }, { id: "imagen", name: "Imagen", description: "Image generation", credits: 10 }, { id: "veo", name: "Veo", description: "Video generation", credits: 30 }] },
  { id: "claude", name: "Claude", status: "Key required", items: [{ id: "claude-sonnet", name: "Claude Sonnet", description: "Balanced reasoning", credits: 12 }, { id: "claude-haiku", name: "Claude Haiku", description: "Fast responses", credits: 6 }, { id: "claude-opus", name: "Claude Opus", description: "Advanced reasoning", credits: 18 }] },
  { id: "sarvam", name: "Sarvam AI", status: "Key required", items: [{ id: "sarvam-bulbul", name: "Bulbul voices", description: "Indian language voice", credits: 8 }, { id: "sarvam-stt", name: "Speech to text", description: "Audio transcription", credits: 6 }, { id: "sarvam-translate", name: "Translation voices", description: "Translation and speech", credits: 10 }] },
  { id: "firecrawl", name: "Firecrawl", status: "Key required", items: [{ id: "firecrawl-scrape", name: "Scrape", description: "Extract one page", credits: 4 }, { id: "firecrawl-crawl", name: "Crawl", description: "Crawl a website", credits: 12 }, { id: "firecrawl-map", name: "Map", description: "Map site URLs", credits: 5 }, { id: "firecrawl-search", name: "Search", description: "Web search", credits: 6 }] }
];

export function marketplaceItems() {
  return marketplaceCatalog.flatMap((category) => category.items.map((item) => ({ ...item, category: category.name })));
}
