export const marketplaceCatalog = [
  { id: "openai", name: "OpenAI", status: "Connected", items: [{ id: "gpt-4.1", name: "GPT-4.1", description: "Generative text", credits: 10 }, { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", description: "Advanced generative text", credits: 15 }, { id: "gpt-image-2", name: "GPT Image 2", description: "Image generation", credits: 8 }, { id: "sora-2", name: "Sora 2", description: "Video generation", credits: 25 }] },
  { id: "astra", name: "Astra", status: "Connected", items: [{ id: "astra-learning", name: "Learning tools", description: "Academy AI tools", credits: 0 }, { id: "astra-codex", name: "Codex workshop", description: "Three-day Codex access", credits: 5 }] },
  { id: "vertex", name: "Vertex AI", status: "Key required", items: [{ id: "gemini-pro", name: "Gemini Pro", description: "Advanced generative text", credits: 12 }, { id: "gemini-flash", name: "Gemini Flash", description: "Fast generative text", credits: 6 }, { id: "imagen", name: "Imagen", description: "Image generation", credits: 10 }, { id: "veo", name: "Veo", description: "Video generation", credits: 30 }] },
  { id: "claude", name: "Claude", status: "Key required", items: [{ id: "claude-sonnet", name: "Claude Sonnet", description: "Balanced reasoning", credits: 12 }, { id: "claude-haiku", name: "Claude Haiku", description: "Fast responses", credits: 6 }, { id: "claude-opus", name: "Claude Opus", description: "Advanced reasoning", credits: 18 }] },
  { id: "sarvam", name: "Sarvam AI", status: "Key required", items: [{ id: "sarvam-m", name: "Sarvam-M", description: "Multilingual Indian language model", credits: 12 }, { id: "sarvam-mayura", name: "Mayura", description: "Indian language translation and transliteration", credits: 10 }, { id: "sarvam-saaras", name: "Saaras", description: "Speech to text with Indian languages", credits: 8 }, { id: "sarvam-bulbul", name: "Bulbul", description: "Text to speech voice generation", credits: 8 }, { id: "sarvam-bulbul-indian", name: "Bulbul Indian voice pack", description: "Hindi and regional language voices", credits: 8 }, { id: "sarvam-bulbul-english", name: "Bulbul English voice pack", description: "Indian English voices", credits: 8 }, { id: "sarvam-voice-streaming", name: "Streaming voice", description: "Low-latency streaming speech", credits: 10 }, { id: "sarvam-ocr", name: "Document OCR", description: "Extract text from documents", credits: 6 }, { id: "sarvam-call-analytics", name: "Call analytics", description: "Transcription and call summaries", credits: 12 }, { id: "sarvam-voice-bots", name: "Voice bots", description: "Conversational voice workflows", credits: 15 }] },
  { id: "firecrawl", name: "Firecrawl", status: "Key required", items: [{ id: "firecrawl-scrape", name: "Scrape", description: "Extract one page", credits: 4 }, { id: "firecrawl-crawl", name: "Crawl", description: "Crawl a website", credits: 12 }, { id: "firecrawl-map", name: "Map", description: "Map site URLs", credits: 5 }, { id: "firecrawl-search", name: "Search", description: "Web search", credits: 6 }] }
];

export function marketplaceItems() {
  return marketplaceCatalog.flatMap((category) => category.items.map((item) => ({ ...item, category: category.name })));
}
